<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_caret_View</name>
   <tag></tag>
   <elementGuidId>1aca5f02-d566-4604-bf01-9839025ab90a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ltr kms-login__body ng-isolate-scope&quot;]/form[@class=&quot;kms-login__form kms-modern-form ng-scope ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]/div[@class=&quot;kms-modern-form__group clearfix&quot;]/div[@class=&quot;btn-group bootstrap-select form-control kms-modern-form__control ng-pristine ng-untouched ng-valid bootstrap-select--focus&quot;]/button[@class=&quot;btn dropdown-toggle btn-default&quot;]/span[@class=&quot;bs-caret&quot;]/span[@class=&quot;caret&quot;]</value>
   </webElementProperties>
</WebElementEntity>
