<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>57899d06-3cc7-4641-83a0-053a0a121740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;advanced-external-file-picker-dialog&quot;]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://kmsqa3:501/kms/CM/FILE_SYSTEM/MANAGER?alias=/FILE_SYSTEM/MANAGER&amp;action=GETLIST&amp;dest_directory=externalFiles&amp;isArchiveDir=Y&amp;pageTitle=Choose%20file&amp;filter=gif,jpg,jpeg,wmf,bmp,pcx,tiff,jfif,jpe,png&amp;viewMode=list&amp;originalFileName=download.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;advanced-external-file-picker-dialog&quot;]/iframe</value>
   </webElementProperties>
</WebElementEntity>
