<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_uploaded</name>
   <tag></tag>
   <elementGuidId>58a6c532-5da7-49fc-aee5-54f0bc300005</elementGuidId>
   <imagePath>img/download.jpg</imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='file-widget-preview-container']/descendant::img[count(. | //*[@ref_element = 'Object Repository/Kms_Page_OR/Roles/Content_Manager/iframe_itemscope']) = count(//*[@ref_element = 'Object Repository/Kms_Page_OR/Roles/Content_Manager/iframe_itemscope'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='file-widget-preview-container']/descendant::img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scr</name>
      <type>Main</type>
      <value>http://kmsqa3:501/archive/externalFiles/download.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Kms_Page_OR/Roles/Content_Manager/iframe_itemscope</value>
   </webElementProperties>
</WebElementEntity>
