<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Authorizations_tab</name>
   <tag></tag>
   <elementGuidId>ccd5fcd4-3eae-4364-8ae5-dda520200a60</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>authorizations-toolbar-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Authorizations</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outer-layout&quot;)/div[@class=&quot;outer-layout-north&quot;]/div[@class=&quot;kms-header&quot;]/header[@class=&quot;top-toolbar&quot;]/div[@class=&quot;top-toolbar__sides&quot;]/div[@class=&quot;top-toolbar__side top-toolbar__side--navigation clearfix&quot;]/ul[@class=&quot;top-toolbar__menu kms-pull--left&quot;]/li[1]/a[@class=&quot;authorizations-toolbar-item&quot;]</value>
   </webElementProperties>
</WebElementEntity>
