<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forum</name>
   <tag></tag>
   <elementGuidId>1b6524b6-facf-4516-9399-f9ded3066f7d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>com.kms.web.layout.forumOverlay.show()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>forum-toolbar-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forum</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outer-layout&quot;)/div[@class=&quot;outer-layout-north&quot;]/div[@class=&quot;kms-header&quot;]/header[@class=&quot;top-toolbar&quot;]/div[@class=&quot;top-toolbar__sides&quot;]/div[@class=&quot;top-toolbar__side top-toolbar__side--navigation clearfix&quot;]/ul[@class=&quot;top-toolbar__menu kms-pull--left&quot;]/li[4]/a[@class=&quot;forum-toolbar-item&quot;]</value>
   </webElementProperties>
</WebElementEntity>
